### ISSUE TITLE
Missing features // TODO

### ISSUE THREAD

**Issue by JojiiOfficial** [JojiiOfficial/LiveBudsCli#29]
- [ ] Find my buds
- [ ] Force firmware reboot
- [ ] Buds original support
- [ ] Actually check for daemon to be ready
- [ ] Custom touchpad actions

**Comment by ecumene** [comment]
I was wondering where the original issue for buds support went, but where it is!

I'm interested in adding original buds support, and you mentioned how to do it on the previous issue (simply make a proof of concept and you'll integrate it). I don't have experience with bluetooth in any way shape or form, but Ive had the buds originals for a few years now and want to use the features on PopOS

I also have a few years experience with rust, so I think wrapping my head around the crates required won't be that hard... Could you walk a noob Bluetooth hacker through how it's done? I'd love to help 😁

**Comment by JojiiOfficial** [comment]
You don't really need experience with bluetooth itself. If you look at the extisting code, you'll see that It's a simple protocol over rfocmm (a serial port protocol over bluetooth). There are 'messages' which represent a command or state information which get transferred over bluetooth. You can have a look at [those examples](https://github.com/JojiiOfficial/GalaxyBuds-rs/tree/master/examples), to get an idea how the transferring is implemented. You'd basically have to find out how the messages are implemented for the buds original. [Here](https://github.com/JojiiOfficial/GalaxyBuds-rs/blob/master/src/message/extended_status_updated.rs) you can see how the message parsing works for the buds live and buds+. To find out how the messages are built up, you can have a look at [this document](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsRFCommProtocol.md), where most of the required calls are already listed. If you have a bit knowledge in C# you can also look at the code from this repo and see how the messages are implemented there.

**Comment by y0uzha** [comment]
hi is this works on ubuntu?

**Comment by JojiiOfficial** [comment]
Yes it does and this is not a question thread. Please create a separate issue for your question next time.
